In [2]:
import keras
import numpy as np

model = keras.Sequential()
# 1000 is max size of rows
# 64 is dimension of the dense embedding 
model.add(keras.layers.Embedding(1000,64))

input_array = np.random.randint(10,size=(5, 10))
print("input array:", input_array)
model.compile('rmsprop','mse')
output_array = model.predict(input_array)
print("embedding:", output_array)
print(output_array.shape)
# 2D tensor with shape: (batch_size, input_length).
# 3D tensor with shape: (batch_size, input_length, output_dim).

input array: [[4 0 0 3 6 9 7 1 2 9]
 [9 2 4 6 2 2 3 9 7 4]
 [0 8 2 2 2 9 4 4 1 8]
 [3 5 5 0 2 7 1 2 7 2]
 [7 1 2 0 1 8 2 6 9 3]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 237ms/step
embedding: [[[-0.04574233 -0.00222445  0.0205554  ...  0.0427304  -0.0182579
    0.03425768]
  [ 0.0060541  -0.03003067  0.03421748 ... -0.00402568 -0.02402965
   -0.04865913]
  [ 0.0060541  -0.03003067  0.03421748 ... -0.00402568 -0.02402965
   -0.04865913]
  ...
  [-0.02114836 -0.00213582 -0.04588914 ...  0.0003156   0.0346518
   -0.04233794]
  [ 0.02657087 -0.01711327 -0.04473257 ...  0.01257345  0.02057532
    0.02022176]
  [ 0.03874402 -0.0218406  -0.03526354 ...  0.017216   -0.0476382
   -0.0244044 ]]

 [[ 0.03874402 -0.0218406  -0.03526354 ...  0.017216   -0.0476382
   -0.0244044 ]
  [ 0.02657087 -0.01711327 -0.04473257 ...  0.01257345  0.02057532
    0.02022176]
  [-0.04574233 -0.00222445  0.0205554  ...  0.0427304  -0.0182579
    0.03425768]
  ...
  [ 0.03874402 -0.0218406  -0.03526354 ...  0.017216   -0.0476382